export const MODEL_ICONS: Record<string, string> = {
	claude: "claude",
	command: "command-a",
	"amazon-nova": "amazon-nova",
	llava: "llava",
	gemini: "gemini",
	gemma: "gemma",
	mistral: "mistral",
	qwen: "qwen",
	"gpt-4": "openai",
	"gpt-3": "openai",
	"gpt-4o": "openai",
	o1: "openai",
	o3: "openai",
	flux: "flux",
	grok: "grok",
	together: "together-ai",
	perplexity: "perplexity",
	deepseek: "deepseek",
	"lm-studio": "lm-studio",
	ai21: "ai21",
	baai: "baai",
	bytedance: "bytedance",
	hunyuan: "hunyuan",
	midjourney: "midjourney",
	meta: "meta",
	stability: "stability",
};

export const PROVIDER_ICONS: Record<string, string> = {
	openai: "openai",
	anthropic: "anthropic",
	google: "google",
	"google-ai-studio": "google",
	googleai: "google",
	mistral: "mistral",
	groq: "groq",
	"perplexity-ai": "perplexity",
	deepseek: "deepseek",
	bedrock: "bedrock",
	"together-ai": "together-ai",
	grok: "grok",
	replicate: "replicate",
	huggingface: "huggingface",
	cohere: "cohere",
	ollama: "ollama",
	"github-models": "github",
	github: "github",
	xai: "xai",
	openrouter: "openrouter",
	"workers-ai": "workers-ai",
	cloudflare: "cloudflare",
};
