import type { ModelConfig } from "../../types";

export const deepseekModelConfig: ModelConfig = {
	"deepseek-chat": {
		name: "DeepSeek Chat",
		matchingModel: "deepseek-chat",
		description:
			"DeepSeek's latest model optimized for coding, analysis, and mathematical tasks with strong reasoning capabilities.",
		provider: "deepseek",
		type: ["text"],
		card: "https://www.prompthub.us/models/deepseek-v3",
		contextWindow: 64000,
		maxTokens: 8000,
		costPer1kInputTokens: 0.00014,
		costPer1kOutputTokens: 0.00028,
		strengths: ["multilingual", "coding", "analysis"],
		contextComplexity: 4,
		reliability: 5,
		speed: 3,
		isFeatured: true,
		includedInRouter: true,
		supportsArtifacts: true,
	},
	"deepseek-reasoner": {
		name: "DeepSeek Reasoner",
		matchingModel: "deepseek-reasoner",
		provider: "deepseek",
		type: ["text"],
		card: "https://www.prompthub.us/models/deepseek-reasoner-r1",
		contextWindow: 64000,
		maxTokens: 8000,
		costPer1kInputTokens: 0.00055,
		costPer1kOutputTokens: 0.00219,
		strengths: ["reasoning", "multilingual", "coding", "analysis"],
		contextComplexity: 4,
		reliability: 5,
		speed: 3,
		isFeatured: true,
		includedInRouter: true,
		supportsArtifacts: true,
	},
	"deepseek-coder-6.7b": {
		name: "DeepSeek Coder 6.7B",
		matchingModel: "@hf/thebloke/deepseek-coder-6.7b-instruct-awq",
		description:
			"Deepseek Coder is composed of a series of code language models, each trained from scratch on 2T tokens, with a composition of 87% code and 13% natural language in both English and Chinese.",
		provider: "workers-ai",
		type: ["coding"],
		card: "https://www.prompthub.us/models/deepseek-coder-6.7b",
		contextWindow: 64000,
		maxTokens: 8000,
		costPer1kInputTokens: 0.00014,
		costPer1kOutputTokens: 0.00028,
		supportsArtifacts: true,
	},
};
