import type { ModelConfig } from "../../types";

export const perplexityModelConfig: ModelConfig = {
	"sonar-deep-research": {
		name: "Perplexity Sonar Deep Research",
		matchingModel: "sonar-deep-research",
		description:
			"Premier research offering with search grounding, supporting advanced queries and follow-ups.",
		provider: "perplexity-ai",
		type: ["text"],
		strengths: ["research", "analysis", "multilingual"],
		isFeatured: true,
		includedInRouter: true,
		costPer1kInputTokens: 0.002,
		costPer1kReasoningTokens: 0.003,
		costPer1kOutputTokens: 0.008,
		costPer1kSearches: 0.005,
	},
	"sonar-reasoning-pro": {
		name: "Perplexity Sonar Reasoning Pro",
		matchingModel: "sonar-reasoning-pro",
		description:
			"Premier reasoning offering powered by DeepSeek R1 with Chain of Thought (CoT).",
		provider: "perplexity-ai",
		type: ["text"],
		strengths: ["reasoning", "multilingual", "coding", "analysis"],
		isFeatured: true,
		includedInRouter: true,
		costPer1kInputTokens: 0.002,
		costPer1kOutputTokens: 0.008,
		costPer1kSearches: 0.005,
	},
	"sonar-reasoning": {
		name: "Perplexity Sonar Reasoning",
		matchingModel: "sonar-reasoning",
		description:
			"Standard reasoning offering with Chain of Thought (CoT) capabilities.",
		provider: "perplexity-ai",
		type: ["text"],
		strengths: ["reasoning", "multilingual", "coding", "analysis"],
		isFeatured: true,
		includedInRouter: true,
		costPer1kInputTokens: 0.001,
		costPer1kOutputTokens: 0.005,
		costPer1kSearches: 0.005,
	},
	"sonar-pro": {
		name: "Perplexity Sonar Pro",
		matchingModel: "sonar-pro",
		description:
			"Premier search offering with search grounding, supporting advanced queries and follow-ups.",
		provider: "perplexity-ai",
		type: ["text"],
		strengths: ["search", "analysis"],
		contextComplexity: 5,
		reliability: 4,
		speed: 3,
		isFeatured: true,
		includedInRouter: true,
		costPer1kInputTokens: 0.003,
		costPer1kOutputTokens: 0.015,
		costPer1kSearches: 0.005,
	},
	sonar: {
		name: "Perplexity Sonar",
		matchingModel: "sonar",
		description:
			"Lightweight offering with search grounding, quicker and cheaper than Sonar Pro.",
		provider: "perplexity-ai",
		type: ["text"],
		strengths: ["search", "analysis"],
		contextComplexity: 4,
		reliability: 4,
		speed: 3,
		isFeatured: true,
		includedInRouter: true,
		costPer1kInputTokens: 0.001,
		costPer1kOutputTokens: 0.001,
		costPer1kSearches: 0.005,
	},
	"r1-1776": {
		name: "Perplexity R1 1776",
		matchingModel: "r1-1776",
		description:
			"R1-1776 is a version of the DeepSeek R1 model that has been post-trained to provide uncensored, unbiased, and factual information.",
		provider: "perplexity-ai",
		type: ["text"],
		strengths: ["reasoning", "multilingual", "coding", "analysis"],
		costPer1kInputTokens: 0.002,
		costPer1kOutputTokens: 0.008,
	},
};
